### ISSUE TITLE
Broken links?

### ISSUE THREAD

**Issue by mohd-anis** [AdsCryptoz22/EasyBuildSystem#1]
Hi,

(1) Noticed the wiki link on https://github.com/AdsCryptoz22/EasyBuildSystem (under **What is This?** section) seems broken?

(2) Same page has the **Quick Start** function also broken? (it goes to https://www.adsstudio12.net)

**Comment by AdsCryptoz22** [comment]
I correct that immediately, I thank you for report this !

**Comment by mohd-anis** [comment]
Thank you!
