### ISSUE TITLE
Asset not working on launch

### ISSUE THREAD

**Issue by xetyr** [AdsCryptoz22/EasyBuildSystem#2]
Hey Bro,

I have some troubles with your asset on a fresh new project.
I've tried to launch it on Unity 2018.3.11f1 and on a 2019 alpha.
When I import the asset, I have some errors in the console : 

Assembly for Assembly Definition File 'Packages/com.unity.package-manager-ui/Tests/Editor/Unity.PackageManagerUI.EditorTests.asmdef' will not be compiled, because it has no scripts associated with it.
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:CompileScripts(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget)
Library\PackageCache\com.unity.package-manager-ui@1.9.11\Editor\Sources\UI\Common\PopupField.cs(8,36): error CS0246: The type or namespace name 'BaseTextElement' could not be found (are you missing a using directive or an assembly reference?)
ExecuteDefaultAction(EventBase)': no suitable method found to override
'PopupField<T>' does not implement interface member 'INotifyValueChanged<T>.SetValueWithoutNotify(T)
'PopupField<T>' does not implement interface member
CheckConsistency: GameObject does not reference component Light. Fixing.

Can you help me pls ?
If you want more details, just ask me

xetyr

**Comment by AdsCryptoz22** [comment]
Try to reset the package manager in the menu items Help => Reset Packages To Default.

**Comment by xetyr** [comment]
I've tried to reset packages to default as you said but it's not working, I also tried to reimport the asset then with the same result

**Comment by AdsCryptoz22** [comment]
What Unity version do you use?

**Comment by xetyr** [comment]
I've tried to launch it on Unity 2018.3.11f1 and on a 2019.2.0a9

**Comment by AdsCryptoz22** [comment]
The recommended version for the system is the 2018.2.
For 2018.3, try to delete the "Packages/manifest.json" manually in your project folder and restart editor.

**Comment by xetyr** [comment]
Ok so, after a deeper testing session I can affirm : 
Load the asset on the 2019 version only resume in freeze during "importing script" and I was obliged to restart Unity.
On 2018.3, I tried to delete manifest.json but I still have errors in the console.


I suppose the best thing to do for me is to developp the building part on 2018.2 and then, upgrade the project to 2018.3 when you'll release a new update. Unfortunatly, I'm obliged to work at least on 2018.3 cause I'm using Bolt' Scripts, which is bugged on 2018.2 and the problem was solved only on 2018.3.

What do you think about this kind of workflow ? And do you plan to update your asset for a fully compatibility with Unity 2018.3+ ?

**Comment by xetyr** [comment]
Solved with update.

Thank's !
