### ISSUE TITLE
2019 Only??

### ISSUE THREAD

**Issue by zrocweb** [AdsCryptoz22/EasyBuildSystem#3]
Why asset only available for 2019 only? Lame!!  Can't download recent version due to not having 2019 installed.  You should really not make assets specific only to latest Unity build.  Most people don't update until truly stable.  Additionally, updating to a current project is not just about your asset.  Need to add some backwards compatibility!?!?!

I purchased this a ways back and am at the point where I want to integrate EBS with my project, using 2018.2.f1.  Nothing works demo wise, nothing but errors.

Thank you

**Comment by AdsCryptoz22** [comment]
Hi,

The samples & integrations require the 2019f1 or high but you can use the
features on all the old unity version.

You can find more information on the wiki Out Of The Box page.

**Comment by zrocweb** [comment]
Hey!

I think you missed the point.  You can not download the latest version from the store anymore due to the limitation on the version. Therefore anything you have fixed in the current version can not be downloaded unless you have 2019+ installed. Which then voids the possibility of being able to use anything from the current version.  As much I want to update to 2019 I'm not doing so yet as I have other assets I have used and I'm not re-writing them, that are are not 100% compatible with 2019.

**Comment by zrocweb** [comment]
.........................

**Comment by AdsCryptoz22** [comment]
Sorry for the late reply, 

Yes the Asset Store prevents the download to the older versions, this for this that the Discord is at your disposal to be able to download all the older versions of the system or integrations.

**Comment by zrocweb** [comment]
Hey! No worries bro. We are all busy these days.. Completely understand.
