### ISSUE TITLE
Unity crashes, when destroying objects with multiple parts like plank wall ect

### ISSUE THREAD

**Issue by TrickShotMLG02** [AdsCryptoz22/EasyBuildSystem#4]
Unity always is crashing, when I klick onto an Object to destroy. But this only happens with objects that are made by multiple parts like the planks wall ect. How can I fix it?

**Comment by AdsCryptoz22** [comment]
Hi,

Sorry for the late reply, you can fix that with the script below, this fix will be available in the next release.
Path : (Easy Build System\Samples & Integrations\Samples\Samples\Contents\ Scripts\Addons\Miscs).
Download : [Here](https://mega.nz/#!INpWWY7Z!LelBELiCkSfsyuhU3F73WHWSu7jazqEmuR8iHB5qMcY).

**Comment by TrickShotMLG02** [comment]
Thank you very much.

**Comment by TrickShotMLG02** [comment]
I just have tried it, but Unity is still crashing

 

Von: AdsCryptoz22 <notifications@github.com> 
Gesendet: Freitag, 14. Juni 2019 12:40
An: AdsCryptoz22/EasyBuildSystem <EasyBuildSystem@noreply.github.com>
Cc: TrickShotMLG02 <tim.schlachter@shinternet.ch>; Author <author@noreply.github.com>
Betreff: Re: [AdsCryptoz22/EasyBuildSystem] Unity crashes, when destroying objects with multiple parts like plank wall ect (#4)

 

Hi,

Sorry for the late reply, you can fix that with the script below, this fix will be available in the next release.
Path : (Easy Build System\Samples & Integrations\Samples\Samples\Contents\ Scripts\Addons\Miscs).
Download : Here <https://mega.nz/#!INpWWY7Z!LelBELiCkSfsyuhU3F73WHWSu7jazqEmuR8iHB5qMcY> .

**Comment by TrickShotMLG02** [comment]
Now i habe fixed it

**Comment by AdsCryptoz22** [comment]
I will try to see this evening, it seems like you're not the only one with this problem.

**Comment by TrickShotMLG02** [comment]
Thank you very much.

**Comment by AdsCryptoz22** [comment]
Sorry for the late reply, you can try the new script below, let me know if this solve anything.
Download : [Here](https://mega.nz/#!wdA0TQTA!kZLOQyREJsW4HBu90JP6iYfI5M5whw8nJo8HmQEUl7w).

**Comment by TrickShotMLG02** [comment]
this solves the general problem, but the objects aren't shattered into multiple parts

**Comment by AdsCryptoz22** [comment]
I tried on one of the scenes of example, the animation during the destruction is correct,
Can you tell me on what scene it produces it? ([Example](https://gyazo.com/5659523315b5cb160055f89555a11b4b)).

**Comment by TrickShotMLG02** [comment]
I have copied the terrain detection scene into my own one and there the objects are disappearing.

**Comment by AdsCryptoz22** [comment]
Do you have conditional physics enabled on your Build Manager?
Try to try this in the demo scene (terrain detection for example) and choose the parts collection (Planks Collection) in the Build Manager (activate also the physics).

**Comment by TrickShotMLG02** [comment]
It worked... Thank you very much
